@startuml
start
 #MediumSpringGreen:get value by the key;
 #MediumSpringGreen:if (value is null) then (yes)
  #MediumSpringGreen:apply mappingFunction(key)\n        to define a new value;
   #MediumSpringGreen:if(new value is null) then (no)
   #MediumSpringGreen:         add new entry or\nupdates value of existing one;
   #MediumSpringGreen:return new value;
   else(yes)
   :return null;
   endif
     else (no)
      :return value;
 endif
stop
@enduml